before_script:

variables:
  MYSQL_DATABASE: project_name
  MYSQL_ROOT_PASSWORD: secret


stages:
  - test
  - deploy

phpunit:php5.6:mysql5.6:
  type: test
  image: php:5.6
  services:
    - mysql:5.6
  script:
    - bash .gitlab-ci.sh
    - php vendor/bin/phpunit --colors

phpunit:php7.0:mysql5.6:
  type: test
  image: php:7.0
  services:
    - mysql:5.6
  script:
    - bash .gitlab-ci.sh
    - php vendor/bin/phpunit --colors

phpunit:php5.5:mysql5.7:
  type: test
  image: php:5.5
  services:
    - mysql:5.7
  script:
    - bash .gitlab-ci.sh
    - php vendor/bin/phpunit --colors

phpunit:php5.6:mysql5.7:
  type: test
  image: php:5.6
  services:
    - mysql:5.7
  script:
    - bash .gitlab-ci.sh
    - php vendor/bin/phpunit --colors

phpunit:php7.0:mysql5.7:
  type: test
  image: php:7.0
  services:
    - mysql:5.7
  script:
    - bash .gitlab-ci.sh
    - php vendor/bin/phpunit --colors
